name: Bug report
description: Create a report to help us improve
title: '[Bug]: '
labels: [ 'bug' ]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your issue.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Fill in the information about the environment you're running the project on.
      value: |
        - Device: [e.g. Mac M1]
        - OS: [e.g. macOS 13.3.1]
        - Project Version: [e.g. 1.0.0]
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false