name: rsmanuf CI (Lint & Test)

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Update manufacturer file"]
    types: [completed]

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Download manuf.txt
        run: wget https://raw.githubusercontent.com/kkrypt0nn/manuf/refs/heads/main/manuf.txt -o src/manuf.txt
      - name: Run rustfmt
        run: cargo fmt --all -- --check --verbose
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Build
        run: cargo build --all --no-default-features --all-features
      - name: Test
        run: cargo test --all --no-default-features --all-features
