name: Monthly Release

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Version Variables
        run: echo "VERSION=2025.2.11" >> $GITHUB_ENV
      #   run: echo "VERSION=$(date +'%-Y.%-m.%-d')" >> $GITHUB_ENV
      - name: Set Release Date
        run: echo "RELEASE_DATE=February 2025" >> $GITHUB_ENV
      #   run: echo "RELEASE_DATE=$(date +'%-B %-Y')" >> $GITHUB_ENV
      - name: Update Cargo.toml Version
        run: sed -i 's/^version = ".*"/version = "'"$VERSION"'"/' Cargo.toml
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Cargo.toml
          git commit -am "chore: Bump version to $VERSION"
          git push
      - name: Create Git Tag
        run: |
          git tag $VERSION
          git push origin $VERSION
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Version ${{ env.VERSION }}
          body: "## ${{ env.RELEASE_DATE }} Update"
          draft: false
          prerelease: false
          make_latest: true
