name: rsmanuf CD (Publish)

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Publish
        run: cargo publish --verbose --all-features --token ${{ secrets.CARGO_TOKEN }}