name: rsmanuf CD (Publish)

on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: ["Monthly Release"]
    types: [completed]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Publish
        run: cargo publish --verbose --all-features --token ${{ secrets.CARGO_TOKEN }}
