name: rsmanuf CD (Publish)

on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: ["Monthly Release"]
    types: [completed]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Download manuf.txt
        run: wget https://raw.githubusercontent.com/kkrypt0nn/manuf/refs/heads/main/manuf.txt -O src/manuf.txt
      - name: Publish
        run: cargo publish --verbose --all-features --token ${{ secrets.CARGO_TOKEN }} --allow-dirty
